-- ==========================================================
-- GESTOR FC - SISTEMA DE GESTÃO PARA ESCOLINHAS DE FUTEBOL
-- BANCO DE DADOS: BDESCOLINHA
-- ==========================================================

CREATE DATABASE IF NOT EXISTS BDESCOLINHA;
USE BDESCOLINHA;

SET FOREIGN_KEY_CHECKS = 0;

-- 1. TABELA DE ESCOLINHAS / CENTROS DE TREINAMENTO
DROP TABLE IF EXISTS TB_PRESENCA;
DROP TABLE IF EXISTS TB_AVALIACAO;
DROP TABLE IF EXISTS TB_AULA;
DROP TABLE IF EXISTS TB_MATRICULA;
DROP TABLE IF EXISTS TB_ALUNO;
DROP TABLE IF EXISTS TB_TURMA;
DROP TABLE IF EXISTS TB_RESPONSAVEL;
DROP TABLE IF EXISTS TB_USUARIO;
DROP TABLE IF EXISTS TB_ESCOLINHA;
CREATE TABLE TB_ESCOLINHA (
    COD_ESCOLINHA INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(20) NULL,
    EMAIL VARCHAR(100) NULL,
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. TABELA DE USUÁRIOS
DROP TABLE IF EXISTS TB_USUARIO;
CREATE TABLE TB_USUARIO (
    COD_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    COD_ESCOLINHA INT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    SENHA_HASH VARCHAR(255) NOT NULL,
    PERFIL ENUM('ADMIN', 'SECRETARIA', 'PROFESSOR', 'RESPONSAVEL') NOT NULL DEFAULT 'ADMIN',
    ATIVO TINYINT(1) DEFAULT 1,
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (COD_ESCOLINHA) REFERENCES TB_ESCOLINHA(COD_ESCOLINHA) ON DELETE CASCADE
);

-- 3. TABELA DE RESPONSÁVEIS
DROP TABLE IF EXISTS TB_RESPONSAVEL;
CREATE TABLE TB_RESPONSAVEL (
    COD_RESPONSAVEL INT AUTO_INCREMENT PRIMARY KEY,
    COD_ESCOLINHA INT NOT NULL,
    COD_USUARIO INT NULL,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    TELEFONE VARCHAR(20),
    EMAIL VARCHAR(100),
    ENDERECO VARCHAR(255),
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (COD_ESCOLINHA) REFERENCES TB_ESCOLINHA(COD_ESCOLINHA) ON DELETE CASCADE,
    FOREIGN KEY (COD_USUARIO) REFERENCES TB_USUARIO(COD_USUARIO) ON DELETE SET NULL,
    UNIQUE (COD_ESCOLINHA, CPF)
);

-- 4. TABELA DE TURMAS
DROP TABLE IF EXISTS TB_TURMA;
CREATE TABLE TB_TURMA (
    COD_TURMA INT AUTO_INCREMENT PRIMARY KEY,
    COD_ESCOLINHA INT NOT NULL,
    COD_PROFESSOR INT NULL,
    NOME VARCHAR(50) NOT NULL,
    FAIXA_ETARIA VARCHAR(30) NOT NULL,
    DIAS_TREINO VARCHAR(100) NOT NULL,
    HORARIO VARCHAR(50) NOT NULL,
    CAPACIDADE INT DEFAULT 25,
    ATIVA TINYINT(1) DEFAULT 1,
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (COD_ESCOLINHA) REFERENCES TB_ESCOLINHA(COD_ESCOLINHA) ON DELETE CASCADE,
    FOREIGN KEY (COD_PROFESSOR) REFERENCES TB_USUARIO(COD_USUARIO) ON DELETE SET NULL
);

-- 5. TABELA DE ALUNOS
DROP TABLE IF EXISTS TB_ALUNO;
CREATE TABLE TB_ALUNO (
    COD_ALUNO INT AUTO_INCREMENT PRIMARY KEY,
    COD_ESCOLINHA INT NOT NULL,
    COD_RESPONSAVEL INT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    POSICAO VARCHAR(30) DEFAULT 'Meio-Campo',
    NUMERO_CAMISA INT NULL,
    STATUS ENUM('ATIVO', 'INATIVO', 'PENDENTE') DEFAULT 'ATIVO',
    DATA_MATRICULA DATE DEFAULT (CURRENT_DATE),
    OBSERVACOES_MEDICAS TEXT NULL,
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (COD_ESCOLINHA) REFERENCES TB_ESCOLINHA(COD_ESCOLINHA) ON DELETE CASCADE,
    FOREIGN KEY (COD_RESPONSAVEL) REFERENCES TB_RESPONSAVEL(COD_RESPONSAVEL) ON DELETE RESTRICT
);

-- 6. MATRÍCULAS: relação N:N entre alunos e turmas
CREATE TABLE TB_MATRICULA (
    COD_MATRICULA INT AUTO_INCREMENT PRIMARY KEY,
    COD_ALUNO INT NOT NULL,
    COD_TURMA INT NOT NULL,
    DATA_MATRICULA DATE NOT NULL,
    STATUS ENUM('ATIVA', 'ENCERRADA') NOT NULL DEFAULT 'ATIVA',
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (COD_ALUNO) REFERENCES TB_ALUNO(COD_ALUNO) ON DELETE CASCADE,
    FOREIGN KEY (COD_TURMA) REFERENCES TB_TURMA(COD_TURMA) ON DELETE CASCADE,
    UNIQUE (COD_ALUNO, COD_TURMA)
);

-- 7. TABELA DE AULAS / SESSÕES DE TREINO
CREATE TABLE TB_AULA (
    COD_AULA INT AUTO_INCREMENT PRIMARY KEY,
    COD_TURMA INT NOT NULL,
    DATA_AULA DATE NOT NULL,
    TEMA_TREINO VARCHAR(100) DEFAULT 'Fundamentos e Coletivo',
    TIPO_TREINO VARCHAR(30) NULL,
    ATRIBUTOS_AVALIAVEIS_JSON JSON NULL,
    OBSERVACAO TEXT NULL,
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (COD_TURMA) REFERENCES TB_TURMA(COD_TURMA) ON DELETE CASCADE
);

-- 8. TABELA DE PRESENÇAS / CHAMADA
CREATE TABLE TB_PRESENCA (
    COD_PRESENCA INT AUTO_INCREMENT PRIMARY KEY,
    COD_AULA INT NOT NULL,
    COD_ALUNO INT NOT NULL,
    PRESENTE TINYINT(1) NOT NULL DEFAULT 1,
    JUSTIFICATIVA VARCHAR(255) NULL,
    FOREIGN KEY (COD_AULA) REFERENCES TB_AULA(COD_AULA) ON DELETE CASCADE,
    FOREIGN KEY (COD_ALUNO) REFERENCES TB_ALUNO(COD_ALUNO) ON DELETE CASCADE,
    UNIQUE (COD_AULA, COD_ALUNO)
);

-- 9. TABELA DE AVALIAÇÕES TÉCNICAS E DE DESEMPENHO
CREATE TABLE TB_AVALIACAO (
    COD_AVALIACAO INT AUTO_INCREMENT PRIMARY KEY,
    COD_AULA INT NULL,
    COD_ALUNO INT NOT NULL,
    COD_PROFESSOR INT NOT NULL,
    DATA_AVALIACAO DATE NOT NULL,
    CRITERIOS_JSON JSON NOT NULL,
    NOTA_GERAL DECIMAL(3,1) NULL,
    OBSERVACAO TEXT NULL,
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (COD_AULA, COD_ALUNO),
    FOREIGN KEY (COD_AULA) REFERENCES TB_AULA(COD_AULA) ON DELETE SET NULL,
    FOREIGN KEY (COD_ALUNO) REFERENCES TB_ALUNO(COD_ALUNO) ON DELETE CASCADE,
    FOREIGN KEY (COD_PROFESSOR) REFERENCES TB_USUARIO(COD_USUARIO) ON DELETE RESTRICT
);

-- ==========================================================
-- DADOS DA ESCOLINHA DEMONSTRATIVA
-- Senha padrão para todos os usuários de teste: 123456
-- Hash: $2y$10$wT355Zg91f6yFw2wRfsB1eJtI0lV9uK0/7d/5N17cZ.R35M2N3y5K
-- ==========================================================

INSERT INTO TB_ESCOLINHA (COD_ESCOLINHA, NOME, TELEFONE, EMAIL) VALUES
(1, 'Escolinha Modelo GestorFC (Demo)', '(11) 98888-7777', 'contato@escolinhamodelo.com');

INSERT INTO TB_USUARIO (COD_USUARIO, COD_ESCOLINHA, NOME, EMAIL, SENHA_HASH, PERFIL, ATIVO) VALUES
(1, 1, 'Carlos Administrador', 'admin@teste.com', '$2y$10$s8miTswfp0Qv3USMA2v0J.8ZPAWg1dLGfIeJRzhIP.u/fVFrbO6Je', 'ADMIN', 1),
(2, 1, 'Mariana Secretária', 'secretaria@teste.com', '$2y$10$s8miTswfp0Qv3USMA2v0J.8ZPAWg1dLGfIeJRzhIP.u/fVFrbO6Je', 'SECRETARIA', 1),
(3, 1, 'Prof. Roberto Silva', 'professor@teste.com', '$2y$10$s8miTswfp0Qv3USMA2v0J.8ZPAWg1dLGfIeJRzhIP.u/fVFrbO6Je', 'PROFESSOR', 1),
(4, 1, 'Fernando Pai (Responsável)', 'responsavel@teste.com', '$2y$10$s8miTswfp0Qv3USMA2v0J.8ZPAWg1dLGfIeJRzhIP.u/fVFrbO6Je', 'RESPONSAVEL', 1);

INSERT INTO TB_RESPONSAVEL (COD_RESPONSAVEL, COD_ESCOLINHA, COD_USUARIO, NOME, CPF, TELEFONE, EMAIL, ENDERECO) VALUES
(1, 1, 4, 'Fernando Oliveira', '111.222.333-44', '(11) 98765-4321', 'responsavel@teste.com', 'Rua das Palmeiras, 120 - São Paulo/SP'),
(2, 1, NULL, 'Patricia Mendes de Souza', '222.333.444-55', '(11) 97654-3210', 'patricia.mendes@email.com', 'Av. Paulista, 1500 - São Paulo/SP'),
(3, 1, NULL, 'Ricardo Antunes Guimarães', '333.444.555-66', '(11) 96543-2109', 'ricardo.antunes@email.com', 'Rua Augusta, 450 - São Paulo/SP');

INSERT INTO TB_TURMA (COD_TURMA, COD_ESCOLINHA, COD_PROFESSOR, NOME, FAIXA_ETARIA, DIAS_TREINO, HORARIO, CAPACIDADE, ATIVA) VALUES
(1, 1, 3, 'Iniciação Sub-09', 'Sub-09 (7 a 9 anos)', 'Terça e Quinta', '08:30 às 10:00', 20, 1),
(2, 1, 3, 'Intermediário Sub-12', 'Sub-12 (10 a 12 anos)', 'Segunda, Quarta e Sexta', '14:00 às 15:30', 25, 1),
(3, 1, 3, 'Competitivo Sub-15', 'Sub-15 (13 a 15 anos)', 'Terça, Quinta e Sábado', '16:00 às 17:45', 22, 1);

INSERT INTO TB_ALUNO (COD_ALUNO, COD_ESCOLINHA, COD_RESPONSAVEL, NOME, DATA_NASCIMENTO, POSICAO, NUMERO_CAMISA, STATUS, DATA_MATRICULA) VALUES
(1, 1, 1, 'Lucas Oliveira (Filho do Fernando)', '2016-04-15', 'Atacante', 9, 'ATIVO', '2024-01-10'),
(2, 1, 1, 'Gabriel Oliveira (Filho do Fernando)', '2013-08-22', 'Meio-Campo', 10, 'ATIVO', '2024-01-10'),
(3, 1, 2, 'Enzo Gabriel Mendes', '2014-02-18', 'Goleiro', 1, 'ATIVO', '2024-02-05'),
(4, 1, 3, 'Matheus Antunes', '2010-11-03', 'Zagueiro', 4, 'ATIVO', '2023-08-15'),
(5, 1, 2, 'Bernardo Mendes', '2017-06-30', 'Lateral Direito', 2, 'ATIVO', '2024-03-01'),
(6, 1, 3, 'Felipe Antunes', '2011-09-12', 'Volante', 5, 'ATIVO', '2023-08-15');

INSERT INTO TB_MATRICULA (COD_MATRICULA, COD_ALUNO, COD_TURMA, DATA_MATRICULA, STATUS) VALUES
(1, 1, 1, '2024-01-10', 'ATIVA'),
(2, 2, 2, '2024-01-10', 'ATIVA'),
(3, 3, 2, '2024-02-05', 'ATIVA'),
(4, 4, 3, '2023-08-15', 'ATIVA'),
(5, 5, 1, '2024-03-01', 'ATIVA'),
(6, 6, 3, '2023-08-15', 'ATIVA');

INSERT INTO TB_AULA (COD_AULA, COD_TURMA, DATA_AULA, TEMA_TREINO, OBSERVACAO) VALUES
(1, 1, CURDATE() - INTERVAL 4 DAY, 'Domínio de bola e condução', 'Treino técnico com foco em coordenação motora'),
(2, 2, CURDATE() - INTERVAL 3 DAY, 'Passe curto e movimentação', 'Exercícios em triângulo e jogo em campo reduzido'),
(3, 3, CURDATE() - INTERVAL 2 DAY, 'Finalização e bolas paradas', 'Cobranças de falta, pênaltis e chutes de média distância'),
(4, 1, CURDATE(), 'Fundamentos de passe e jogo coletivo', 'Treino realizado com excelente participação');

INSERT INTO TB_PRESENCA (COD_AULA, COD_ALUNO, PRESENTE, JUSTIFICATIVA) VALUES
(1, 1, 1, NULL),
(1, 5, 1, NULL),
(2, 2, 1, NULL),
(2, 3, 0, 'Consulta médica agendada'),
(3, 4, 1, NULL),
(3, 6, 1, NULL),
(4, 1, 1, NULL),
(4, 5, 1, NULL);

INSERT INTO TB_AVALIACAO (COD_AVALIACAO, COD_ALUNO, COD_PROFESSOR, DATA_AVALIACAO, CRITERIOS_JSON, NOTA_GERAL, OBSERVACAO) VALUES
(1, 1, 3, CURDATE() - INTERVAL 10 DAY, '{"passe": 8.5, "finalizacao": 9.0, "posicionamento": 8.0, "fisico": 7.5, "disciplina": 9.5}', 8.5, 'Excelente evolução na finalização e ótimo comportamento em equipe.'),
(2, 2, 3, CURDATE() - INTERVAL 10 DAY, '{"passe": 9.0, "finalizacao": 8.0, "posicionamento": 9.5, "fisico": 8.5, "disciplina": 9.0}', 8.8, 'Ótima visão de jogo, atua muito bem na distribuição de jogadas no meio-campo.'),
(3, 4, 3, CURDATE() - INTERVAL 15 DAY, '{"passe": 7.5, "finalizacao": 6.5, "posicionamento": 9.0, "fisico": 9.0, "disciplina": 8.0}', 8.0, 'Excelente porte físico e marcação individual sólida.');

SET FOREIGN_KEY_CHECKS = 1;
