-- Modulo de jogos e estatisticas individuais.
-- Execute uma unica vez em cada banco existente.

CREATE TABLE TB_JOGO (
    COD_JOGO INT AUTO_INCREMENT PRIMARY KEY,
    COD_TURMA INT NOT NULL,
    ADVERSARIO VARCHAR(100) NOT NULL,
    DATA_JOGO DATE NOT NULL,
    HORARIO TIME NULL,
    LOCAL VARCHAR(150) NULL,
    GOLS_ESCOLINHA TINYINT UNSIGNED NULL,
    GOLS_ADVERSARIO TINYINT UNSIGNED NULL,
    OBSERVACOES TEXT NULL,
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX IDX_JOGO_DATA (DATA_JOGO),
    FOREIGN KEY (COD_TURMA) REFERENCES TB_TURMA(COD_TURMA) ON DELETE CASCADE
);

CREATE TABLE TB_JOGO_ATLETA (
    COD_JOGO_ATLETA INT AUTO_INCREMENT PRIMARY KEY,
    COD_JOGO INT NOT NULL,
    COD_ALUNO INT NOT NULL,
    TITULAR TINYINT(1) NOT NULL DEFAULT 0,
    PARTICIPOU TINYINT(1) NOT NULL DEFAULT 1,
    GOLS TINYINT UNSIGNED NOT NULL DEFAULT 0,
    ASSISTENCIAS TINYINT UNSIGNED NOT NULL DEFAULT 0,
    UNIQUE (COD_JOGO, COD_ALUNO),
    INDEX IDX_JOGO_ATLETA_ALUNO (COD_ALUNO),
    FOREIGN KEY (COD_JOGO) REFERENCES TB_JOGO(COD_JOGO) ON DELETE CASCADE,
    FOREIGN KEY (COD_ALUNO) REFERENCES TB_ALUNO(COD_ALUNO) ON DELETE CASCADE
);
