-- Centro de notificações. Execute uma vez em cada banco já existente.

CREATE TABLE TB_NOTIFICACAO (
    COD_NOTIFICACAO INT AUTO_INCREMENT PRIMARY KEY,
    COD_ESCOLINHA INT NOT NULL,
    COD_USUARIO INT NOT NULL,
    TIPO ENUM('NOVO_TREINO', 'ALTERACAO_TREINO', 'NOVA_AVALIACAO', 'NOVA_MATRICULA', 'SOLICITACAO_CAMISA', 'SOLICITACAO_ACEITA', 'SOLICITACAO_RECUSADA', 'APROVACAO_PROFESSOR', 'NOVO_JOGO', 'NOVO_EVENTO', 'OUTRA_ALTERACAO') NOT NULL,
    TITULO VARCHAR(120) NOT NULL,
    DESCRICAO TEXT NOT NULL,
    URL VARCHAR(255) NULL,
    LIDA TINYINT(1) NOT NULL DEFAULT 0,
    CRIADO_EM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX IDX_NOTIFICACAO_USUARIO (COD_ESCOLINHA, COD_USUARIO, LIDA, CRIADO_EM),
    FOREIGN KEY (COD_ESCOLINHA) REFERENCES TB_ESCOLINHA(COD_ESCOLINHA) ON DELETE CASCADE,
    FOREIGN KEY (COD_USUARIO) REFERENCES TB_USUARIO(COD_USUARIO) ON DELETE CASCADE
);
