-- Perfil de acesso de aluno, vínculo único com o cadastro esportivo e metas pessoais.
-- Execute uma única vez em cada banco existente, após a migração de jogos.

ALTER TABLE TB_USUARIO
    MODIFY PERFIL ENUM('ADMIN', 'SECRETARIA', 'PROFESSOR', 'RESPONSAVEL', 'ALUNO') NOT NULL DEFAULT 'ADMIN';

ALTER TABLE TB_ALUNO
    ADD COLUMN COD_USUARIO INT NULL UNIQUE AFTER COD_RESPONSAVEL,
    ADD CONSTRAINT FK_ALUNO_USUARIO FOREIGN KEY (COD_USUARIO)
        REFERENCES TB_USUARIO(COD_USUARIO) ON DELETE SET NULL;

CREATE TABLE TB_META_ATLETA (
    COD_META INT AUTO_INCREMENT PRIMARY KEY,
    COD_ALUNO INT NOT NULL,
    CRIADO_POR INT NOT NULL,
    TIPO ENUM('OVERALL', 'ATRIBUTO', 'GOLS', 'ASSISTENCIAS') NOT NULL,
    ATRIBUTO VARCHAR(30) NULL,
    VALOR_ALVO DECIMAL(6,2) NOT NULL,
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (COD_ALUNO) REFERENCES TB_ALUNO(COD_ALUNO) ON DELETE CASCADE,
    FOREIGN KEY (CRIADO_POR) REFERENCES TB_USUARIO(COD_USUARIO) ON DELETE CASCADE
);
