<?php
require_once __DIR__ . '/includes/layout.php'; require_once __DIR__ . '/config/database.php';
checkRole(['ADMIN', 'SECRETARIA']); $db = getDB(); $escolinha = currentEscolinhaId(); $edit = null;
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    checkCsrf(); $action = $_POST['action'] ?? ''; $id = (int) ($_POST['id'] ?? 0);
    if ($action === 'delete') { $db->prepare('DELETE FROM TB_TURMA WHERE COD_TURMA = ? AND COD_ESCOLINHA = ?')->execute([$id, $escolinha]); flash('success', 'Turma excluída.'); go('turmas.php'); }
    $nome = trim($_POST['nome'] ?? ''); $faixa = trim($_POST['faixa_etaria'] ?? ''); $dias = trim($_POST['dias_treino'] ?? ''); $horario = trim($_POST['horario'] ?? ''); $capacidade = (int) ($_POST['capacidade'] ?? 0); $professor = (int) ($_POST['cod_professor'] ?? 0); $ativa = isset($_POST['ativa']) ? 1 : 0;
    if ($nome === '' || $faixa === '' || $dias === '' || $horario === '' || $capacidade < 1) { flash('error', 'Preencha todos os campos e informe capacidade maior que zero.'); go('turmas.php' . ($id ? '?editar=' . $id : '')); }
    if ($professor) { $ok = $db->prepare("SELECT 1 FROM TB_USUARIO WHERE COD_USUARIO = ? AND COD_ESCOLINHA = ? AND PERFIL = 'PROFESSOR'"); $ok->execute([$professor, $escolinha]); if (!$ok->fetchColumn()) { flash('error', 'Professor inválido.'); go('turmas.php'); } }
    if ($action === 'create') { $db->prepare('INSERT INTO TB_TURMA (COD_ESCOLINHA, COD_PROFESSOR, NOME, FAIXA_ETARIA, DIAS_TREINO, HORARIO, CAPACIDADE, ATIVA) VALUES (?, ?, ?, ?, ?, ?, ?, ?)')->execute([$escolinha, $professor ?: null, $nome, $faixa, $dias, $horario, $capacidade, $ativa]); flash('success', 'Turma cadastrada.'); }
    if ($action === 'update') { $db->prepare('UPDATE TB_TURMA SET COD_PROFESSOR = ?, NOME = ?, FAIXA_ETARIA = ?, DIAS_TREINO = ?, HORARIO = ?, CAPACIDADE = ?, ATIVA = ? WHERE COD_TURMA = ? AND COD_ESCOLINHA = ?')->execute([$professor ?: null, $nome, $faixa, $dias, $horario, $capacidade, $ativa, $id, $escolinha]); flash('success', 'Turma atualizada.'); }
    go('turmas.php');
}
if (isset($_GET['editar'])) { $q = $db->prepare('SELECT * FROM TB_TURMA WHERE COD_TURMA = ? AND COD_ESCOLINHA = ?'); $q->execute([(int) $_GET['editar'], $escolinha]); $edit = $q->fetch(); if (!$edit) { flash('error', 'Turma não encontrada.'); go('turmas.php'); } }
$professores = $db->prepare("SELECT COD_USUARIO, NOME FROM TB_USUARIO WHERE COD_ESCOLINHA = ? AND PERFIL = 'PROFESSOR' AND ATIVO = 1 ORDER BY NOME"); $professores->execute([$escolinha]); $professores = $professores->fetchAll();
$q = $db->prepare("SELECT t.*, u.NOME AS PROFESSOR, COUNT(m.COD_MATRICULA) AS MATRICULADOS FROM TB_TURMA t LEFT JOIN TB_USUARIO u ON u.COD_USUARIO = t.COD_PROFESSOR LEFT JOIN TB_MATRICULA m ON m.COD_TURMA = t.COD_TURMA AND m.STATUS = 'ATIVA' WHERE t.COD_ESCOLINHA = ? GROUP BY t.COD_TURMA ORDER BY t.NOME"); $q->execute([$escolinha]); $lista = $q->fetchAll();
pageStart('Turmas'); $v = function ($key, $default = '') use ($edit) { return e($edit[$key] ?? $default); };
?>
<section><h2><?= $edit ? 'Editar turma' : 'Nova turma' ?></h2><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrfToken()) ?>"><input type="hidden" name="action" value="<?= $edit ? 'update' : 'create' ?>"><?php if ($edit): ?><input type="hidden" name="id" value="<?= (int) $edit['COD_TURMA'] ?>"><?php endif; ?><label>Nome<input required name="nome" value="<?= $v('NOME') ?>"></label><label>Faixa etária<input required name="faixa_etaria" value="<?= $v('FAIXA_ETARIA') ?>" placeholder="Ex.: Sub-12 (10 a 12 anos)"></label><label>Dias de treino<input required name="dias_treino" value="<?= $v('DIAS_TREINO') ?>"></label><label>Horário<input required name="horario" value="<?= $v('HORARIO') ?>"></label><label>Capacidade<input required min="1" type="number" name="capacidade" value="<?= $v('CAPACIDADE', 25) ?>"></label><label>Professor<select name="cod_professor"><option value="">Não definido</option><?php foreach ($professores as $p): ?><option value="<?= (int) $p['COD_USUARIO'] ?>" <?= ($edit['COD_PROFESSOR'] ?? '') == $p['COD_USUARIO'] ? 'selected' : '' ?>><?= e($p['NOME']) ?></option><?php endforeach; ?></select></label><label><input type="checkbox" name="ativa" <?= ($edit['ATIVA'] ?? 1) ? 'checked' : '' ?>> Turma ativa</label><div><?php actionButton($edit ? 'Salvar alterações' : 'Cadastrar turma'); ?><?php if ($edit): ?><a href="turmas.php">Cancelar</a><?php endif; ?></div></form></section>
<section><div><table><thead><tr><th>Turma</th><th>Professor</th><th>Horário</th><th>Vagas</th><th>Ações</th></tr></thead><tbody><?php foreach ($lista as $t): ?><tr><td><?= e($t['NOME']) ?><br><span><?= e($t['FAIXA_ETARIA']) ?></span></td><td><?= e($t['PROFESSOR'] ?: 'Não definido') ?></td><td><?= e($t['DIAS_TREINO']) ?><br><?= e($t['HORARIO']) ?></td><td><?= (int) $t['MATRICULADOS'] ?>/<?= (int) $t['CAPACIDADE'] ?></td><td><button type="button" class="acao-tabela" data-modal-url="turmas.php?mini=1&amp;editar=<?= (int) $t['COD_TURMA'] ?>" data-modal-titulo="Editar turma">Editar</button><form method="post" onsubmit="return confirm('Excluir esta turma?');"><input type="hidden" name="csrf_token" value="<?= e(csrfToken()) ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= (int) $t['COD_TURMA'] ?>"><button>Excluir</button></form></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php pageEnd(); ?>
