<?php
require_once __DIR__ . '/includes/layout.php'; require_once __DIR__ . '/config/database.php';
checkRole(['ADMIN', 'SECRETARIA']); $db = getDB(); $escolinha = currentEscolinhaId(); $edit = null;
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    checkCsrf(); $action = $_POST['action'] ?? ''; $id = (int) ($_POST['id'] ?? 0);
    if ($action === 'delete') { $db->prepare('DELETE FROM TB_TURMA WHERE COD_TURMA = ? AND COD_ESCOLINHA = ?')->execute([$id, $escolinha]); flash('success', 'Turma excluída.'); go('turmas.php'); }
    $nome = trim($_POST['nome'] ?? ''); $faixa = trim($_POST['faixa_etaria'] ?? ''); $dias = trim($_POST['dias_treino'] ?? ''); $horario = trim($_POST['horario'] ?? ''); $capacidade = (int) ($_POST['capacidade'] ?? 0); $professor = (int) ($_POST['cod_professor'] ?? 0); $ativa = isset($_POST['ativa']) ? 1 : 0;
    if ($nome === '' || $faixa === '' || $dias === '' || $horario === '' || $capacidade < 1) { flash('error', 'Preencha todos os campos e informe capacidade maior que zero.'); go('turmas.php' . ($id ? '?editar=' . $id : '')); }
    if ($professor) { $ok = $db->prepare("SELECT 1 FROM TB_USUARIO WHERE COD_USUARIO = ? AND COD_ESCOLINHA = ? AND PERFIL = 'PROFESSOR'"); $ok->execute([$professor, $escolinha]); if (!$ok->fetchColumn()) { flash('error', 'Professor inválido.'); go('turmas.php'); } }
    if ($action === 'create') { $db->prepare('INSERT INTO TB_TURMA (COD_ESCOLINHA, COD_PROFESSOR, NOME, FAIXA_ETARIA, DIAS_TREINO, HORARIO, CAPACIDADE, ATIVA) VALUES (?, ?, ?, ?, ?, ?, ?, ?)')->execute([$escolinha, $professor ?: null, $nome, $faixa, $dias, $horario, $capacidade, $ativa]); flash('success', 'Turma cadastrada.'); }
    if ($action === 'update') { $db->prepare('UPDATE TB_TURMA SET COD_PROFESSOR = ?, NOME = ?, FAIXA_ETARIA = ?, DIAS_TREINO = ?, HORARIO = ?, CAPACIDADE = ?, ATIVA = ? WHERE COD_TURMA = ? AND COD_ESCOLINHA = ?')->execute([$professor ?: null, $nome, $faixa, $dias, $horario, $capacidade, $ativa, $id, $escolinha]); flash('success', 'Turma atualizada.'); }
    go('turmas.php');
}
if (isset($_GET['editar'])) { $q = $db->prepare('SELECT * FROM TB_TURMA WHERE COD_TURMA = ? AND COD_ESCOLINHA = ?'); $q->execute([(int) $_GET['editar'], $escolinha]); $edit = $q->fetch(); if (!$edit) { flash('error', 'Turma não encontrada.'); go('turmas.php'); } }
$professores = $db->prepare("SELECT COD_USUARIO, NOME FROM TB_USUARIO WHERE COD_ESCOLINHA = ? AND PERFIL = 'PROFESSOR' AND ATIVO = 1 ORDER BY NOME"); $professores->execute([$escolinha]); $professores = $professores->fetchAll();
$q = $db->prepare("SELECT t.*, u.NOME AS PROFESSOR, COUNT(m.COD_MATRICULA) AS MATRICULADOS FROM TB_TURMA t LEFT JOIN TB_USUARIO u ON u.COD_USUARIO = t.COD_PROFESSOR LEFT JOIN TB_MATRICULA m ON m.COD_TURMA = t.COD_TURMA AND m.STATUS = 'ATIVA' WHERE t.COD_ESCOLINHA = ? GROUP BY t.COD_TURMA ORDER BY t.NOME"); $q->execute([$escolinha]); $lista = $q->fetchAll();
pageStart('Turmas'); $v = function ($key, $default = '') use ($edit) { return e($edit[$key] ?? $default); };
?>
<section class="mb-8 rounded-xl border border-stone-200 bg-white p-5 shadow-sm"><h2 class="mb-4 font-bold text-emerald-950"><?= $edit ? 'Editar turma' : 'Nova turma' ?></h2><form method="post" class="grid gap-4 md:grid-cols-2"><input type="hidden" name="csrf_token" value="<?= e(csrfToken()) ?>"><input type="hidden" name="action" value="<?= $edit ? 'update' : 'create' ?>"><?php if ($edit): ?><input type="hidden" name="id" value="<?= (int) $edit['COD_TURMA'] ?>"><?php endif; ?><label class="text-sm font-medium">Nome<input required name="nome" value="<?= $v('NOME') ?>" class="mt-1 w-full rounded border p-2"></label><label class="text-sm font-medium">Faixa etária<input required name="faixa_etaria" value="<?= $v('FAIXA_ETARIA') ?>" placeholder="Ex.: Sub-12 (10 a 12 anos)" class="mt-1 w-full rounded border p-2"></label><label class="text-sm font-medium">Dias de treino<input required name="dias_treino" value="<?= $v('DIAS_TREINO') ?>" class="mt-1 w-full rounded border p-2"></label><label class="text-sm font-medium">Horário<input required name="horario" value="<?= $v('HORARIO') ?>" class="mt-1 w-full rounded border p-2"></label><label class="text-sm font-medium">Capacidade<input required min="1" type="number" name="capacidade" value="<?= $v('CAPACIDADE', 25) ?>" class="mt-1 w-full rounded border p-2"></label><label class="text-sm font-medium">Professor<select name="cod_professor" class="mt-1 w-full rounded border p-2"><option value="">Não definido</option><?php foreach ($professores as $p): ?><option value="<?= (int) $p['COD_USUARIO'] ?>" <?= ($edit['COD_PROFESSOR'] ?? '') == $p['COD_USUARIO'] ? 'selected' : '' ?>><?= e($p['NOME']) ?></option><?php endforeach; ?></select></label><label class="flex items-center gap-2 text-sm font-medium"><input type="checkbox" name="ativa" <?= ($edit['ATIVA'] ?? 1) ? 'checked' : '' ?>> Turma ativa</label><div class="flex gap-3"><?php actionButton($edit ? 'Salvar alterações' : 'Cadastrar turma'); ?><?php if ($edit): ?><a class="rounded-lg border px-4 py-2" href="turmas.php">Cancelar</a><?php endif; ?></div></form></section>
<section class="overflow-hidden rounded-xl border bg-white shadow-sm"><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-emerald-950 text-white"><tr><th class="p-3">Turma</th><th class="p-3">Professor</th><th class="p-3">Horário</th><th class="p-3">Vagas</th><th class="p-3">Ações</th></tr></thead><tbody><?php foreach ($lista as $t): ?><tr class="border-t"><td class="p-3 font-medium"><?= e($t['NOME']) ?><br><span class="text-xs text-slate-500"><?= e($t['FAIXA_ETARIA']) ?></span></td><td class="p-3"><?= e($t['PROFESSOR'] ?: 'Não definido') ?></td><td class="p-3"><?= e($t['DIAS_TREINO']) ?><br><?= e($t['HORARIO']) ?></td><td class="p-3"><?= (int) $t['MATRICULADOS'] ?>/<?= (int) $t['CAPACIDADE'] ?></td><td class="flex gap-2 p-3"><a class="text-emerald-800 underline" href="turmas.php?editar=<?= (int) $t['COD_TURMA'] ?>">Editar</a><form method="post" onsubmit="return confirm('Excluir esta turma?');"><input type="hidden" name="csrf_token" value="<?= e(csrfToken()) ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= (int) $t['COD_TURMA'] ?>"><button class="text-rose-700 underline">Excluir</button></form></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php pageEnd(); ?>
